CREATE GENERATOR  GEN_ID_EMPRESA;

SET TERM ^ ;

CREATE TRIGGER INSERE_EMPRESA FOR EMPRESA
ACTIVE BEFORE insert POSITION 0
AS
    BEGIN
        NEW.ID_EMPRESA=GEN_ID(GEN_ID_EMPRESA,1);
     END^
SET TERM ; ^



