/*CRIA O GENERATOR PARA O CAMPO ID USUARIO*/
CREATE GENERATOR GEN_ID_USUARIO;

/*CRIA A TRIGGER PARA USUARIO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_USUARIO FOR usuario ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_USUARIO=gen_id(GEN_ID_USUARIO,1);
END^
SET TERM ; ^

INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES ('GUSTAVO','2201','ADM','22.01.2003');

INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES ('ANA','2002','ADM','21.05.2002');

SELECT * FROM USUARIO

/*CLIENTE GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_CLIENTE;

SET TERM ^ ;

CREATE TRIGGER INSERE_ID_CLIENTE FOR CLIENTE ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_CLIENTE=gen_id(GEN_ID_CLIENTE,1);
END^
SET TERM ; ^


/*EMPRESA GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_EMPRESA;

/*CRIA A TRIGGER PARA EMPRESA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_EMPRESA FOR EMPRESA ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_EMPRESA=gen_id(GEN_ID_EMPRESA,1);
END^
SET TERM ; ^


/*FORNECEDORES GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_FORNECEDOR;

/*CRIA A TRIGGER PARA FORNECEDORES*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FORNECEDOR FOR FORNECEDOR ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_FORNECEDOR=gen_id(GEN_ID_FORNECEDOR,1);
END^
SET TERM ; ^



/*PRODUTOS GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_PRODUTO;

/*CRIA A TRIGGER PARA PRODUTO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_PRODUTO FOR PRODUTO ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_PRODUTO=gen_id(GEN_ID_PRODUTO,1);
END^
SET TERM ; ^


/*FORMA PGTO GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_FORMA_PGTO;

/*CRIA A TRIGGER PARA FORMA DE PAGAMENTO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FORMA_PGTO FOR FORMA_PGTO ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_FORMA_PGTO=gen_id(GEN_ID_FORMA_PGTO,1);
END^
SET TERM ; ^


/*COMPRAS GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_COMPRA;

/*CRIA A TRIGGER PARA COMPRA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_COMPRA FOR COMPRA ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_COMPRA=gen_id(GEN_ID_COMPRA,1);
END^
SET TERM ; ^

/*CRIA O GENERATOR PARA O CAMPO ID USUARIO*/
CREATE GENERATOR GEN_ID_USUARIO;

/*CRIA A TRIGGER PARA USUARIO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_USUARIO FOR usuario ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_USUARIO=gen_id(GEN_ID_USUARIO,1);
END^
SET TERM ; ^

INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES ('GUSTAVO','2201','ADM','22.01.2003');

INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES ('ANA','2002','ADM','21.05.2002');

SELECT * FROM USUARIO

/*CLIENTE GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_CLIENTE;

SET TERM ^ ;

CREATE TRIGGER INSERE_ID_CLIENTE FOR CLIENTE ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_CLIENTE=gen_id(GEN_ID_CLIENTE,1);
END^
SET TERM ; ^


/*EMPRESA GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_EMPRESA;

/*CRIA A TRIGGER PARA EMPRESA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_EMPRESA FOR EMPRESA ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_EMPRESA=gen_id(GEN_ID_EMPRESA,1);
END^
SET TERM ; ^


/*FORNECEDORES GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_FORNECEDOR;

/*CRIA A TRIGGER PARA FORNECEDORES*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FORNECEDOR FOR FORNECEDOR ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_FORNECEDOR=gen_id(GEN_ID_FORNECEDOR,1);
END^
SET TERM ; ^



/*PRODUTOS GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_PRODUTO;

/*CRIA A TRIGGER PARA PRODUTO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_PRODUTO FOR PRODUTO ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_PRODUTO=gen_id(GEN_ID_PRODUTO,1);
END^
SET TERM ; ^


/*FORMA PGTO GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_FORMA_PGTO;

/*CRIA A TRIGGER PARA FORMA DE PAGAMENTO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FORMA_PGTO FOR FORMA_PGTO ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_FORMA_PGTO=gen_id(GEN_ID_FORMA_PGTO,1);
END^
SET TERM ; ^


/*VENDAS GENERATOR E TRIGGERS*/

CREATE GENERATOR GEN_ID_VENDA;

/*CRIA A TRIGGER PARA VENDAS*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_VENDA FOR VENDA ACTIVE
BEFORE INSERT position 0
AS
BEGIN
    NEW.ID_VENDA=gen_id(GEN_ID_VENDA,1);
END^
SET TERM ; ^
